version: "3.7"

services:
  go: &go
    build:
      context: ./docker/armgo
    volumes:
      - "./:/src"
      - "go-cache:/go"
    working_dir: /src/bot
  build_arm:
    <<: *go
    entrypoint: build/make.sh
    environment:
      - CC=arm-linux-gnueabi-gcc
      - GOARCH=arm
    env_file:
      - .build.env
  build_arm64:
    <<: *go
    entrypoint: build/make.sh
    environment:
      - CC=aarch64-linux-gnu-gcc
      - GOARCH=arm64
    env_file:
      - .build.env
  build_amd64:
    <<: *go
    entrypoint: build/make.sh
    environment:
      - GOARCH=amd64
    env_file:
      - .build.env

volumes:
  go-cache:
