version: "3.7"

services:
  go: &go
    build:
      context: ./docker/armgo
    volumes:
      - "./:/src"
      - "go-cache:/go"
    working_dir: /src/bot
    environment:
      - uid=1000
      - gid=1000
      - CGO_ENABLED=1
      - GOOS=linux
  build_arm:
    <<: *go
    entrypoint: sh build/make.sh
    environment:
      - CC=arm-linux-gnueabi-gcc
      - GOARCH=arm
  build_arm64:
    <<: *go
    entrypoint: sh build/make.sh
    environment:
      - CC=aarch64-linux-gnu-gcc
      - GOARCH=arm64
  build_amd64:
    <<: *go
    entrypoint: sh build/make.sh
    environment:
      - GOARCH=amd64

volumes:
  go-cache:
