version: "3.7"

services:
  go: &go
    build:
      context: ./docker/armgo
    volumes:
      - "./:/src"
      - "go-cache:/.cache"
    working_dir: /src/bot
    environment:
      - uid=1000
      - gid=1000
  build_arm:
    <<: *go
    entrypoint: sh ./build/make_arm.sh
  build_arm64:
    <<: *go
    entrypoint: sh ./build/make_arm64.sh
  build_amd64:
    <<: *go
    entrypoint: sh ./build/make_amd64.sh

volumes:
  db-data:
    driver: local
  go-cache:
