version: "3.7"

services:
  go: &go
    build:
      context: ./docker/armgo
    volumes:
      - "./:/src"
    working_dir: /src
  build_arm:
    <<: *go
    entrypoint: sh ./build/make_arm.sh
    volumes:
      - "./:/src"
    working_dir: /src
  build_arm64:
    <<: *go
    entrypoint: sh ./build/make_arm64.sh
    volumes:
      - "./:/src"
    working_dir: /src
  build_amd64:
    <<: *go
    entrypoint: sh ./build/make_amd64.sh
    volumes:
      - "./:/src"
    working_dir: /src

volumes:
  db-data:
    driver: local
