version: '3.7'

services:
  go: &go
    build:
      context: ./docker/go
    volumes:
      - "./:/src"
    working_dir: /src
    links:
      - postgres
    depends_on:
      - postgres

  build_arm:
    build:
      context: ./docker/armgo
    entrypoint: go build main.go
    volumes:
      - "./:/src"
    working_dir: /src

  afk_bot:
    <<: *go
    entrypoint: go run afk-bot/afk-bot.go
  claim_bot:
    <<: *go
    entrypoint: go run claim-bot/claim-bot.go
  nleave_ban_bot:
    <<: *go
    entrypoint: go run nleave-ban-bot/nleave-ban-bot.go

  postgres:
    image: postgres:11-alpine
    restart: always
    env_file: .env
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
    driver: local