version: "3.7"

services:
  go: &go
    build:
      context: ./docker/armgo
    volumes:
      - "./:/src"
      - "go-cache:/.cache"
    working_dir: /src/bot
    environment:
      - uid=1000
      - gid=1000
  go_web:
    <<: *go
    entrypoint: go run web/web.go
    ports:
     - "8888:8080"
  build_arm:
    <<: *go
    entrypoint: sh ./build/make_arm.sh
  build_arm64:
    <<: *go
    entrypoint: sh ./build/make_arm64.sh
  build_amd64:
    <<: *go
    entrypoint: sh ./build/make_amd64.sh
  yarn: &yarn
    build:
      context: ./docker/yarn
    volumes:
      - "./yarn:/app"
      - "./templates:/templates"
    working_dir: /app
  yarn-install:
    <<: *yarn
    entrypoint: yarn install
  yarn-dev:
    <<: *yarn
    entrypoint: yarn start
    ports:
      - "3001:3000"
  yarn-build:
    <<: *yarn
    entrypoint: yarn build

volumes:
  db-data:
    driver: local
  go-cache: