version: "3.7"

services:
  go: &go
    image: alpine
    volumes:
      - "./:/bot"
    working_dir: /bot
  go_bot:
    <<: *go
    entrypoint: ./discord-bot
    restart: always
  go_web:
    <<: *go
    entrypoint: ./discord-web
    restart: always

volumes:
  go-cache:
