version: "3.7"

services:
  go: &go
    build:
      context: ./docker/armgo
    volumes:
      - "./:/src"
    working_dir: /src
  build_arm:
    <<: *go
    user: "${UID}:${GID}"
    entrypoint: sh ./build/make_arm.sh
    volumes:
      - "./:/src"
    working_dir: /src
  build_arm64:
    <<: *go
    user: "${UID}:${GID}"
    entrypoint: sh ./build/make_arm64.sh
    volumes:
      - "./:/src"
    working_dir: /src
  build_amd64:
    <<: *go
    user: "${UID}:${GID}"
    entrypoint: sh ./build/make_amd64.sh
    volumes:
      - "./:/src"
    working_dir: /src
  yarn: &yarn
    build:
      context: ./docker/yarn
    volumes:
      - "./yarn:/app"
      - "./templates:/templates"
    working_dir: /app
  yarn-install:
    <<: *yarn
    entrypoint: yarn install
  yarn-dev:
    <<: *yarn
    entrypoint: yarn start
    ports:
      - "3001:3000"
  yarn-build:
    <<: *yarn
    entrypoint: yarn build

volumes:
  db-data:
    driver: local
